# Generated by Django 5.1 on 2024-08-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('待出貨', '待出貨'), ('待付款', '待付款'), ('已出貨', '已出貨'), ('已取消', '已取消')], default='待出貨', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('box_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales_periods.salesperiod')),
            ],
            options={
                'verbose_name': '訂單列表',
                'verbose_name_plural': '訂單列表',
                'db_table': 'order',
            },
        ),
    ]
