# Generated by Django 5.1 on 2024-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_pickup_date_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('備貨中', '備貨中'), ('待出貨', '待出貨'), ('待付款', '待付款'), ('已出貨', '已出貨'), ('已取消', '已取消')], default='備貨中', max_length=20),
        ),
    ]
