# Generated by Django 5.1 on 2024-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
