# Generated by Django 5.1 on 2024-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_is_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
