# Generated by Django 5.1 on 2024-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
