# Generated by Django 5.1 on 2024-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
