# Generated by Django 5.1 on 2024-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_eate', models.DateField()),
                ('status', models.CharField(choices=[('預備中', '預備中'), ('開放訂購', '開放訂購'), ('已結束', '已結束')], default='預備中', max_length=20)),
            ],
            options={
                'verbose_name': '檔期',
                'verbose_name_plural': '檔期',
                'db_table': 'sales_period',
            },
        ),
    ]
