# Generated by Django 5.1 on 2024-09-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_periods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperiod',
            old_name='end_eate',
            new_name='end_date',
        ),
    ]
