# Generated by Django 5.1 on 2024-10-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_periods', '0002_rename_end_eate_salesperiod_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperiod',
            name='status',
        ),
    ]
